### ISSUE TITLE
required squircy2/data/ directory missing

### ISSUE THREAD

**Issue by bpiraeus** [tyler-sommer/squircy2#13]
bp@ghost:~/WORK$ go get -u github.com/tyler-sommer/squircy2/cmd/squircy2
package github.com/tyler-sommer/squircy2/data: cannot find package "github.com/tyler-sommer/squircy2/data" in any of:
        /usr/local/go/src/github.com/tyler-sommer/squircy2/data (from $GOROOT)
        /home/bp/WORK/src/github.com/tyler-sommer/squircy2/data (from $GOPATH)

While there appears to be historical artifacts from the initial commit, it's unclear what the intention was, but if I had to guess...

manager.go:
- "github.com/tyler-sommer/squircy2/data"
+ "github.com/HouzuoGuo/tiedot/db"

- database := data.NewDatabaseConnection(m.conf.RootPath)
+ database, err := db.OpenDB(m.conf.RootPath)

However script/vm.go also references squircy2/data and attempts
db := data.NewGenericRepository(m.database, coll)

and also has 3 calls to data.GenericModel  ... 

seems like there's a major commit missing somewhere?

**Comment by tyler-sommer** [comment]
Very embarrassing! Seems when I migrated that package I didn't realize that `data` was in my global gitignore.

I committed the package and have pushed the package to github.

Thanks for the bug report!

**Comment by bpiraeus** [comment]
If that were the least of the mistakes I've made over the years, I'd be pleased as punch :) Glad to hear it was an easy fix, and I look forward to playing with the code more, 2am on a caffeine binge is probably not the best way to solve things.
