### ISSUE TITLE
irc.PRIVMSG not working

### ISSUE THREAD

**Issue by rikvdh** [tyler-sommer/squircy2#2]
Hi,

I have a script which tries to use the irc.PRIVMSG event. But it doesn't work.

``` js
function sudoCoffee(code, target, nick, message) {
    Irc.Privmsg("#e", "a");
    if (message.indexOf("coffee") >= 0) {
      Irc.Privmsg("#e", "seen");
    } else {
      Irc.Privmsg("#e", "not seen");
    }
}

bind('irc.PRIVMSG', sudoCoffee);
```

It tells "a" on the channel "#e", but no "seen" or "not seen" is sent. Also when I change "a" to, for example, nick to print the nickname squircy2 crashes.

It would be nice to have some examples on how to use different events and write scripts.

Greetings,

Rik

**Comment by tyler-sommer** [comment]
Hi @rikvdh, thanks for trying out squircy!

I have updated the documentation with some more examples, and fixed broken examples.

Your handler will only receive the first parameter. It will be an object with various properties, differing depending on which event you're handling.

For example:

``` js
bind('irc.PRIVMSG', function(e) {
    if (e.Message.indexOf("coffee") >= 0) {
        // message contained "coffee"
        // Additional properties for e include: e.Code, e.Target, and e.Nick
    }
});
```

You can iterate over the properties of the object with `e.forEach()` or a traditional `for` loop.

## 

As far as the crash, I definitely think that's an issue. I tried to reproduce the issue with this script:

```
bind("irc.PRIVMSG", function(code, target, nick, message) {
    console.log(nick);
});
```

However, the bot does not crash, the console simply prints "undefined". Could you provide a repro case for the crash?

Cheers

**Comment by tyler-sommer** [comment]
I'm closing this as it seems to no longer be relevant. Please feel free to open another issue. Thanks!
