### ISSUE TITLE
SSL Support?

### ISSUE THREAD

**Issue by ghost** [tyler-sommer/squircy2#4]
Just curious if there exists currently SSL support. I am fairly certain that the underlying go-irc-event library supports it, is there a way to configure it as such currently or not yet exposed?

**Comment by tyler-sommer** [comment]
Yep, go-irc-event supports TLS (see https://github.com/thoj/go-ircevent#commands) but its not currently exposed by squircy: https://github.com/tyler-sommer/squircy2/blob/master/squircy/irc/irc.go#L53

**Comment by ghost** [comment]
Addressed by pull #8

**Comment by tyler-sommer** [comment]
Closed by #8
